#!/usr/bin/env perl

use strict;
use warnings;
use 5.010;

use JSON::PP;
use File::Slurp;
use Template;

my $json_text = File::Slurp::read_file( 'comparison.json' );

my $sections = JSON::PP->new->utf8->decode($json_text);

for my $section ( @{$sections} ) {
    my $heading = $section->{heading};
    my $abilities = $section->{abilities};
}


my $vars = {
    sections => $sections,
};

my $tt = Template->new;
$tt->process( 'chart.ttml', $vars ) or die $tt->error;
